<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $report->name }}</title>
    <style>
        @page { margin: 34px; }
        body { color: #172b4d; font-family: "DejaVu Sans", sans-serif; font-size: 9px; }
        .brand { color: #146c94; font-size: 11px; font-weight: bold; letter-spacing: 1.2px; text-transform: uppercase; }
        h1 { font-size: 22px; margin: 8px 0 4px; }
        .meta { border-bottom: 2px solid #d8e7ee; color: #667085; margin-bottom: 18px; padding-bottom: 12px; }
        .summary { background: #edf7fa; border-left: 4px solid #19a7a0; margin-bottom: 16px; padding: 10px 12px; }
        table { border-collapse: collapse; table-layout: fixed; width: 100%; }
        th { background: #146c94; color: white; padding: 7px 6px; text-align: left; }
        td { border-bottom: 1px solid #d8e0e8; padding: 6px; vertical-align: top; word-wrap: break-word; }
        tr:nth-child(even) td { background: #f7fafb; }
        .footer { color: #98a2b3; font-size: 8px; margin-top: 16px; }
    </style>
</head>
<body>
    <div class="brand">Ask GAHolding</div>
    <h1>{{ $report->name }}</h1>
    <div class="meta">
        {{ ucfirst(str_replace('_', ' ', $report->type)) }} · Generated {{ optional($snapshot->generated_at)->format('d M Y, H:i T') }}
    </div>
    <div class="summary">
        <strong>{{ number_format(count($rows)) }} records</strong>
        @if($report->description) · {{ $report->description }} @endif
    </div>
    <table>
        <thead>
            <tr>
                @foreach(($report->definition['columns'] ?? []) as $column)
                    <th>{{ $column['label'] }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse($rows as $row)
                <tr>
                    @foreach(($report->definition['columns'] ?? []) as $column)
                        @php($value = data_get($row, $column['key']))
                        <td>
                            @if($value === null || $value === '')
                                —
                            @elseif(($column['type'] ?? null) === 'currency' && is_numeric($value))
                                AED {{ number_format((float) $value, 2) }}
                            @elseif(($column['type'] ?? null) === 'number' && is_numeric($value))
                                {{ number_format((float) $value, 2) }}
                            @elseif(($column['type'] ?? null) === 'percentage' && is_numeric($value))
                                {{ number_format((float) $value, 1) }}%
                            @else
                                {{ $value }}
                            @endif
                        </td>
                    @endforeach
                </tr>
            @empty
                <tr><td colspan="{{ max(1, count($report->definition['columns'] ?? [])) }}">No records match the selected filters.</td></tr>
            @endforelse
        </tbody>
    </table>
    <div class="footer">Confidential business report · Generated by Ask GAHolding · Snapshot #{{ $snapshot->id }}</div>
</body>
</html>
